### ISSUE TITLE
Hospedagem da aplicação

### ISSUE THREAD

**Issue by Antonio91378** [igortuag/chested-champions#1]
Eu lembro que você tinha hospedado essa aplicação, ela ainda está disponível ? 
se sim poderia mandar o link ?

**Comment by igortuag** [comment]
@Antonio91378 Sim, e eu fiz outra em nextjs que estou usando atualmente. https://nextjs-lol-champion-picker.vercel.app/
o repo é: https://github.com/igortuag/nextjs-lol-champion-picker

O deploy dessa aqui esta em: https://awesome-jang-72cf9c.netlify.app/

Me diga qual ira usar e quais funcionalidades você gostaria de ver. Eu por exemplo pretendo adicionar algo para exportar e importar a seleção e uns filtros/search.

**Comment by Antonio91378** [comment]
> @Antonio91378 Sim, e eu fiz outra em nextjs que estou usando atualmente. https://nextjs-lol-champion-picker.vercel.app/ o repo é: https://github.com/igortuag/nextjs-lol-champion-picker
> 
> O deploy dessa aqui esta em: https://awesome-jang-72cf9c.netlify.app/
> 
> Me diga qual ira usar e quais funcionalidades você gostaria de ver. Eu por exemplo pretendo adicionar algo para exportar e importar a seleção e uns filtros/search.

Gostei dessa que vc fez com next, ficou legal o link pras builds. Ficaria interessante também criar uma barra de pesquisa, eu posso tentar fazer isso, caso goste e queira fazer um merge depois ^^. Pros cards dos campeões vc consumiu uma API ?
=======
ahh achei olhando no seu repo --'http://ddragon.leagueoflegends.com/cdn/12.3.1/data/en_US/champion.json' muito bacana men 👏👏
